### ISSUE TITLE
Rethinking package

### ISSUE THREAD

**Issue by jpiaskowski** [cran-task-views/Bayesian#24]
Hello,

I recommend [rethinking](https://github.com/rmcelreath/rethinking) for inclusion, perhaps under the category for learning Bayesian. I realize this is not on CRAN, but it does accompany a widely read book, [Statistical Rethinking](https://xcelab.net/rm/statistical-rethinking/), and the repo itself has 1.8k stars, evidence of some community vetting.

**Comment by jongheepark** [comment]
Yes, good idea. I will add it. Thanks.

**Comment by jongheepark** [comment]
Well, I checked CRAN package list and rethinking is not there. It's only in github. So it can't be added. It's the general taskview policy that only CRAN packages are introduced.

**Comment by jpiaskowski** [comment]
Github packages allowed, but the focus is on CRAN packages.

**Comment by jongheepark** [comment]
Well, but we've never included non-CRAN packages because "CRAN task views aim to provide some guidance which packages on CRAN are relevant for tasks related to a certain topic." https://cran.r-project.org/web/views/

**Comment by jpiaskowski** [comment]
That's up to you, but as a co-maintainer of the agricultural and MixedModels task views, I can say we have several github packages since the goal is to provide a resource for users. As mentioned in my original post: "I realize this is not on CRAN, but it does accompany a widely read book, [Statistical Rethinking](https://xcelab.net/rm/statistical-rethinking/), and the repo itself has 1.8k stars, evidence of some community vetting."
