### ISSUE TITLE
Add mvgam to the Time series models section

### ISSUE THREAD

**Issue by nicholasjclark** [cran-task-views/Bayesian#46]
Thanks very much for maintaining this useful resource. I've just had [a package, `mvgam` released to CRAN](https://cran.rstudio.com/web/packages/mvgam/index.html) that fits a wide range of State Space time series models using Stan for Bayesian inference. I'm hoping to have it added to this list, where it would be most appropriate under the **Time series models** section. Very happy to provide a blurb if that is useful. Thanks again

**Comment by jongheepark** [comment]
mvgam is added. Thanks.

**Comment by nicholasjclark** [comment]
Thanks very much
