### ISSUE TITLE
Package 'BMS' has been archived on CRAN for more than 60 days

### ISSUE THREAD

**Issue by statmath-it** [cran-task-views/Bayesian#8]
Package [BMS](https://CRAN.R-project.org/package=BMS) is currently listed in CRAN Task View [Bayesian](https://CRAN.R-project.org/view=Bayesian) but the package has actually been archived for more than 60 days on CRAN.  Often this indicates that the package is currently not sufficiently actively maintained and should be excluded from the task view.

Alternatively, you might also consider reaching out to the authors of the package and encourage (or even help) them to bring the package back to CRAN.

In any case, the situation should be resolved in the next four weeks. If the package does not seem to be brought back to CRAN, please exclude it from the task view.

**Comment by zeileis** [comment]
Just for your information: I have been in contact with the BMS authors in April, June, and again today, see: https://github.com/cran-task-views/Econometrics/issues/11

I still have some hope that they will resubmit the package in the next weeks. But if this hasn't happened in the next 2-3 weeks it's probably best to remove it from the task views.

**Comment by zeileis** [comment]
`BMS` has been resurrected on CRAN so this issue can be closed.
